import { Link } from 'react-router-dom';
import { Sparkles, BookOpen, Brain, Zap, ArrowRight, ChevronRight } from 'lucide-react';

const features = [
  {
    icon: Brain,
    title: 'AI-Powered Curriculum',
    desc: 'Gemini AI generates structured, multi-module courses with chain-of-thought reasoning.',
  },
  {
    icon: Zap,
    title: 'Instant Generation',
    desc: 'Redis caching serves repeat topics in milliseconds. 60% faster on cached queries.',
  },
  {
    icon: BookOpen,
    title: 'Rich Lesson Content',
    desc: 'Code blocks, MCQs, video recommendations, and markdown—all generated by AI.',
  },
];

export default function LandingPage() {
  return (
    <div style={{ overflow: 'hidden' }}>
      {/* ─── HERO ─── */}
      <section style={{
        position: 'relative',
        minHeight: 'calc(100vh - 64px)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        padding: 'var(--space-3xl) var(--space-lg)',
      }}>
        {/* Ambient glow */}
        <div style={{
          position: 'absolute',
          top: '10%', left: '50%',
          transform: 'translateX(-50%)',
          width: 600, height: 600,
          background: 'radial-gradient(circle, var(--accent-glow) 0%, transparent 70%)',
          pointerEvents: 'none',
          filter: 'blur(80px)',
          opacity: 0.6,
        }} />

        <div className="animate-fade-in-up" style={{
          position: 'relative',
          textAlign: 'center',
          maxWidth: 720,
        }}>
          {/* Badge */}
          <div className="badge" style={{
            marginBottom: 'var(--space-lg)',
            padding: '0.35rem 0.9rem',
            fontSize: '0.75rem',
          }}>
            <Sparkles size={12} /> Powered by Gemini 2.5 Flash & LangChain
          </div>

          <h1 style={{
            fontSize: 'clamp(2.5rem, 6vw, 4rem)',
            fontWeight: 900,
            lineHeight: 1.1,
            letterSpacing: '-0.03em',
            marginBottom: 'var(--space-lg)',
          }}>
            Transform any topic into a{' '}
            <span style={{
              background: 'var(--accent-gradient)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
            }}>complete course</span>
          </h1>

          <p style={{
            fontSize: '1.15rem',
            color: 'var(--text-secondary)',
            lineHeight: 1.7,
            maxWidth: 560,
            margin: '0 auto var(--space-xl)',
          }}>
            Enter a topic. Our agentic AI pipeline generates structured modules, 
            rich lessons with code, quizzes, and video—grounded by RAG for accuracy.
          </p>

          {/* CTA */}
          <div style={{ display: 'flex', gap: 'var(--space-md)', justifyContent: 'center', flexWrap: 'wrap' }}>
            <Link to="/register" className="btn btn-primary btn-lg" style={{
              gap: 'var(--space-sm)',
            }}>
              Start Learning Free <ArrowRight size={18} />
            </Link>
            <Link to="/login" className="btn btn-secondary btn-lg">
              Sign In
            </Link>
          </div>
        </div>
      </section>

      {/* ─── FEATURES ─── */}
      <section style={{
        maxWidth: 1000,
        margin: '0 auto',
        padding: 'var(--space-3xl) var(--space-lg)',
      }}>
        <div style={{ textAlign: 'center', marginBottom: 'var(--space-2xl)' }} className="animate-fade-in">
          <h2 style={{
            fontSize: '1.75rem', fontWeight: 800, letterSpacing: '-0.02em',
            marginBottom: 'var(--space-sm)',
          }}>How it works</h2>
          <p style={{ color: 'var(--text-secondary)', maxWidth: 480, margin: '0 auto' }}>
            Three simple steps to go from idea to a full, structured curriculum.
          </p>
        </div>

        <div className="stagger-children" style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
          gap: 'var(--space-lg)',
        }}>
          {features.map((f, i) => (
            <div key={i} className="card" style={{
              display: 'flex', flexDirection: 'column', gap: 'var(--space-md)',
            }}>
              <div style={{
                width: 44, height: 44,
                borderRadius: 'var(--radius-md)',
                background: 'var(--accent-glow)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
              }}>
                <f.icon size={20} style={{ color: 'var(--accent-primary)' }} />
              </div>
              <h3 style={{ fontSize: '1.05rem', fontWeight: 700 }}>{f.title}</h3>
              <p style={{ color: 'var(--text-secondary)', fontSize: '0.875rem', lineHeight: 1.7 }}>
                {f.desc}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* ─── CTA BANNER ─── */}
      <section style={{
        maxWidth: 900,
        margin: '0 auto var(--space-3xl)',
        padding: 'var(--space-lg)',
      }}>
        <div className="animate-fade-in" style={{
          background: 'var(--accent-gradient)',
          borderRadius: 'var(--radius-xl)',
          padding: 'var(--space-2xl) var(--space-xl)',
          textAlign: 'center',
          position: 'relative',
          overflow: 'hidden',
        }}>
          <div style={{
            position: 'absolute', inset: 0,
            background: 'radial-gradient(circle at 30% 50%, rgba(255,255,255,0.1), transparent 60%)',
            pointerEvents: 'none',
          }} />
          <h2 style={{
            fontSize: '1.5rem', fontWeight: 800, color: '#fff',
            marginBottom: 'var(--space-sm)', position: 'relative',
          }}>Ready to build your first course?</h2>
          <p style={{
            color: 'rgba(255,255,255,0.8)', marginBottom: 'var(--space-lg)',
            fontSize: '0.95rem', position: 'relative',
          }}>
            Join learners who are creating personalized curriculums in seconds.
          </p>
          <Link to="/register" style={{
            display: 'inline-flex', alignItems: 'center', gap: 'var(--space-sm)',
            background: '#fff', color: '#4f46e5',
            padding: '0.75rem 1.75rem', borderRadius: 'var(--radius-md)',
            fontWeight: 700, fontSize: '0.9rem',
            transition: 'transform var(--duration-base) var(--ease-out)',
            position: 'relative',
          }}
            onMouseEnter={e => e.currentTarget.style.transform = 'translateY(-2px)'}
            onMouseLeave={e => e.currentTarget.style.transform = 'translateY(0)'}
          >
            Get Started <ChevronRight size={16} />
          </Link>
        </div>
      </section>

      {/* ─── FOOTER ─── */}
      <footer style={{
        borderTop: '1px solid var(--border-primary)',
        padding: 'var(--space-xl) var(--space-lg)',
        textAlign: 'center',
        color: 'var(--text-tertiary)',
        fontSize: '0.8rem',
      }}>
        © {new Date().getFullYear()} CourseForge — Built with Gemini, LangChain & RAG
      </footer>
    </div>
  );
}
