import { useParams, Link } from "react-router-dom";

const Lesson = () => {
  const { id } = useParams();

  return (
    <div className="py-8 max-w-3xl mx-auto">
      <Link to={`/course/${id.substring(0, 1)}`} className="text-primary-light text-sm font-semibold hover:underline mb-8 inline-block">&larr; Back to Course</Link>

      <h1 className="text-3xl font-bold mb-6 text-white">Lesson {id}: Core Concepts</h1>
      
      <div className="prose prose-invert prose-indigo max-w-none mb-12">
        <p className="text-gray-300 leading-relaxed mb-4">
          Welcome to this lesson. Here you will learn the fundamental concepts required to master this topic. The content below is generated by the Gemini API and structured for optimal learning.
        </p>
        <h2 className="text-xl font-semibold text-white mt-8 mb-4">1. Introduction</h2>
        <p className="text-gray-300 leading-relaxed mb-4">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula. Sed auctor neque eu tellus rhoncus ut eleifend nibh porttitor. Ut in nulla enim. Phasellus molestie magna non est bibendum non venenatis nisl tempor.
        </p>
        <pre className="bg-[#1a1b26] p-4 rounded-lg overflow-x-auto border border-gray-800 my-6">
          <code className="text-sm font-mono text-green-400">console.log("Hello, World!");</code>
        </pre>
      </div>

      <div className="flex justify-between items-center border-t border-indigo-500/20 pt-6">
        <button className="px-5 py-2 rounded-lg border border-indigo-500/30 text-gray-300 hover:bg-white/5 transition-colors">
          Previous Lesson
        </button>
        <button className="px-5 py-2 rounded-lg bg-primary hover:bg-primary-dark text-white font-semibold transition-colors flex items-center gap-2">
          <span>Mark Complete</span>
          <span>&rarr;</span>
        </button>
      </div>
    </div>
  );
};

export default Lesson;
